<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGZLD5ZT\srcApp_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGZLD5ZT/srcApp_KernelProdDebugContainer.php') {
    touch(__DIR__.'/ContainerGZLD5ZT.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdDebugContainer::class, false)) {
    \class_alias(\ContainerGZLD5ZT\srcApp_KernelProdDebugContainer::class, srcApp_KernelProdDebugContainer::class, false);
}

return new \ContainerGZLD5ZT\srcApp_KernelProdDebugContainer([
    'container.build_hash' => 'GZLD5ZT',
    'container.build_id' => '04dc9554',
    'container.build_time' => 1578091720,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGZLD5ZT');
